services:
  photo-organizer:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./photos:/app/photos
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: ["python", "main.py", "/app/photos", "--organize"]

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
      - "8888:8888"
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/htmlcov
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash
