version: '3.8'

services:
  photo-organizer:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: python main.py
